# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-07 08:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('addr', models.CharField(max_length=50)),
                ('type', models.IntegerField()),
                ('money', models.DecimalField(decimal_places=8, max_digits=20)),
                ('fee', models.DecimalField(decimal_places=8, max_digits=20)),
                ('create_time', models.DateTimeField(default=datetime.datetime(2017, 8, 7, 8, 28, 20, 249200, tzinfo=utc), verbose_name='时间')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('type', models.IntegerField()),
                ('yt', models.IntegerField()),
                ('addr', models.CharField(max_length=50)),
                ('money', models.DecimalField(decimal_places=8, max_digits=20)),
                ('status', models.IntegerField(default=1, verbose_name='状态')),
            ],
        ),
    ]
