# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-06 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('type', models.IntegerField()),
                ('addr', models.CharField(max_length=50)),
                ('money', models.DecimalField(decimal_places=8, max_digits=20)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
