# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ise', '0002_auto_20170815_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='config',
            name='icoCount',
            field=models.IntegerField(default=0, verbose_name='sec已发量'),
        ),
        migrations.AlterField(
            model_name='config',
            name='secCount',
            field=models.IntegerField(default=0, verbose_name='sec总量'),
        ),
    ]
